# Generated by Django 5.2 on 2025-05-20 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('kategorieid', models.AutoField(db_column='KategorieID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45, unique=True)),
            ],
            options={
                'db_table': 'kategorie',
            },
        ),
        migrations.CreateModel(
            name='Nutzer',
            fields=[
                ('email', models.CharField(db_column='Email', max_length=30, unique=True)),
                ('passwort', models.CharField(db_column='Passwort', max_length=45)),
                ('eingeloggt', models.IntegerField(db_column='Eingeloggt')),
                ('gesperrt', models.IntegerField(db_column='Gesperrt')),
                ('nutzerid', models.AutoField(db_column='NutzerID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nutzer',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('beschreibung', models.CharField(blank=True, db_column='Beschreibung', max_length=60, null=True)),
                ('fotoid', models.AutoField(db_column='FotoID', primary_key=True, serialize=False)),
                ('hochladedatum', models.DateField(blank=True, db_column='HochladeDatum', null=True)),
                ('gesamtbewertung', models.FloatField(db_column='Gesamtbewertung')),
                ('foto', models.TextField(db_column='Foto')),
                ('kategorieid', models.ForeignKey(db_column='KategorieID', on_delete=django.db.models.deletion.DO_NOTHING, to='SammelPlatt.kategorie')),
            ],
            options={
                'db_table': 'foto',
            },
        ),
        migrations.CreateModel(
            name='Bewertung',
            fields=[
                ('sternezahl', models.IntegerField(db_column='sterneZahl')),
                ('bewertungid', models.AutoField(db_column='BewertungID', primary_key=True, serialize=False)),
                ('titel', models.CharField(db_column='Titel', max_length=25)),
                ('beschreibung', models.CharField(blank=True, db_column='Beschreibung', max_length=60, null=True)),
                ('fotoid', models.ForeignKey(db_column='FotoID', on_delete=django.db.models.deletion.DO_NOTHING, to='SammelPlatt.foto')),
                ('nutzerid', models.ForeignKey(db_column='NutzerID', on_delete=django.db.models.deletion.DO_NOTHING, to='SammelPlatt.nutzer')),
            ],
            options={
                'db_table': 'bewertung',
            },
        ),
        migrations.CreateModel(
            name='Ordner',
            fields=[
                ('ordid', models.AutoField(db_column='OrdID', primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=45, unique=True)),
                ('pfad', models.CharField(max_length=45)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('inordner', models.ForeignKey(blank=True, db_column='inOrdner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SammelPlatt.ordner')),
            ],
            options={
                'db_table': 'ordner',
            },
        ),
        migrations.AddField(
            model_name='foto',
            name='ordid',
            field=models.ForeignKey(db_column='OrdID', on_delete=django.db.models.deletion.DO_NOTHING, to='SammelPlatt.ordner'),
        ),
    ]
